### ISSUE TITLE
Physics Model and visualization

### ISSUE THREAD

**Issue by kaphleamrit2** [geant4-dna/molecular-docs#54]
How to apply two different physics models in two different regions (For example DNAphysics-2 in world volume and Dnaphysics-4 in DNA volume) for a single run?
Also, visualization is not working. When I run vis. mac only the world box appears (used **/dnageom/drawCellVolumes true**). How to visualize all the structures of DNA properly? 

Thanks.

AK

**Comment by hoangtranIP2i** [comment]
Dear, 

1/ for the physical models combination, please see the microdosimetry example (geant4/example/extended/medical/dna/microdosimetry).

2/ The visualization will not work for human_cell.mac and ecoli.mac cause of memory limitation. You can try with cylinders.mac

**Comment by hoangtranIP2i** [comment]
more info can be found in https://geant4-forum.web.cern.ch
